### ISSUE TITLE
org.test.data.Country is missing ;-)

### ISSUE THREAD

**Issue by svenruppert** [lemagnecharle/vaadin-mem-sample#1]

**Comment by lemagnecharle** [comment]
Danke Sven, gitignore hat mir da einen Strich durch die Rechnung gemacht.
Jetzt konnte ich die Klasse nicht vom Arbeitsrechner ziehen, da der
Netzwerk troubles hat, also schnell nachgecoded.

Sollte jetzt funktionieren!

Vielen Dank für deine Hilfe,

liebe Grüße

Karli

2018-06-10 11:00 GMT+02:00 Sven Ruppert <notifications@github.com>:

**Comment by svenruppert** [comment]
ok, danke
